In [1]:
import numpy as np

In [2]:
liste = [1,2,3,4,5,6,7,8]
a = np.array(liste)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [6]:
a.shape  # 8'e 0'lık nir vektör

(8,)

In [7]:
a[0]

1

In [8]:
a[2] = 8

In [9]:
a

array([1, 2, 8, 4, 5, 6, 7, 8])

In [10]:
b = np.array([[1,2,3], [6,7,8]])

In [11]:
b.shape

(2, 3)

In [12]:
b[1,1] = 0

b

array([[1, 2, 3],
       [6, 0, 8]])

In [13]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [14]:
c.shape

(3, 3)

In [15]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
c[1,1]

5

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((2,2), -1)

array([[-1, -1],
       [-1, -1]])

In [22]:
np.empty((3,4))  # 0'a yakın sayılar döndürür

array([[1.03111143e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [6.23059386e-307, 1.61590357e+184, 6.50956290e-091,
        6.23367032e+174],
       [1.26192560e-076, 3.29477521e-032, 3.99910963e+252,
        2.22522596e-306]])

In [23]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.arange(5,60,3)  # 5'den 60'a kadar 3 er 3 er yazdır

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [28]:
np.linspace(2, 30, 5)  # 2 ve 30 arasını eşit 5 parçaya böl. start stop dahil edilir

array([ 2.,  9., 16., 23., 30.])

In [29]:
np.random.random((3,3))  # 0 ile 1 arasında random değerler atar

array([[0.50809544, 0.51652441, 0.363224  ],
       [0.73153764, 0.78022534, 0.29810767],
       [0.78094137, 0.73305077, 0.55915819]])

In [30]:
np.random.randint(5,10, size=(4,4))  # 4'e 4 matrixte 5 ile 10 arasında rastgele değerler ata

array([[6, 8, 5, 9],
       [9, 7, 7, 5],
       [7, 7, 8, 9],
       [5, 5, 5, 7]])

In [31]:
z = np.random.randint(2,15, size = (5,3))

In [32]:
z.shape

(5, 3)

In [33]:
z.reshape(3,5)

array([[ 9,  3,  3, 10, 10],
       [ 2, 11, 12,  5,  9],
       [ 5,  3,  8,  3,  6]])

In [34]:
z.ravel()  # matrixi tek satırda toplar

array([ 9,  3,  3, 10, 10,  2, 11, 12,  5,  9,  5,  3,  8,  3,  6])

In [35]:
z.max()

12

In [36]:
z.min()

2

In [37]:
z.argmax()

7

In [38]:
z.argmin()

5

## Stacking

In [39]:
a = np.array([[1,2], [3,4]])
b = np.array([[-1,3], [7,9]])

In [40]:
a

array([[1, 2],
       [3, 4]])

In [41]:
b

array([[-1,  3],
       [ 7,  9]])

In [42]:
np.hstack((a,b))  # concatenate ile aynı şeyi yapar

array([[ 1,  2, -1,  3],
       [ 3,  4,  7,  9]])

In [43]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [-1,  3],
       [ 7,  9]])

In [44]:
dizi = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)

In [45]:
dizi

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# concatenate

In [47]:
dizi_1 = np.array([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)

dizi_1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
np.concatenate([dizi, dizi_1], axis = 1)

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [49]:
np.concatenate([dizi, dizi_1], axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [50]:
array_1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [51]:
array_1.shape

(3, 4)

In [52]:
array_1[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [57]:
array_2 = array_1.copy()  # copy ile kopyaladık ki orijinal veri bozulmasın

In [54]:
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
array_2[1,1] = -6

array_2

array([[ 1,  2,  3,  4],
       [ 5, -6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

m.shape

(4, 3)

In [59]:
ikidenbuyuk = m>2

In [60]:
m[ikidenbuyuk]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
m[m>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [63]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [65]:
x + y  # aynı index'te olanları toplar

array([[ 6,  8],
       [10, 12]])

In [66]:
x - y

array([[-4, -4],
       [-4, -4]])

In [67]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [68]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [69]:
x*y

array([[ 5, 12],
       [21, 32]])

In [71]:
np.dot(x,y)  # matrix çarpımı yaptık. farklı boyutları da çarpabilir.

array([[19, 22],
       [43, 50]])

In [72]:
x@y  # dot ile aynı işlem

array([[19, 22],
       [43, 50]])

In [73]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [74]:
x

array([[1, 2],
       [3, 4]])

In [75]:
x**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [79]:
np.square(x)  # karesini al

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [77]:
x1 = np.square(x)

In [80]:
np.sqrt(x1)  # kökünü al

array([[1., 2.],
       [3., 4.]])

In [82]:
np.exp(3)  # e üzeri 3

20.085536923187668

In [83]:
np.log(100)

4.605170185988092

In [84]:
np.log10(100)

2.0

In [85]:
t = np.array([np.pi/6, np.pi/2, np.pi/3])

In [86]:
np.sin(t)

array([0.5      , 1.       , 0.8660254])